name: Green Squares

on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 10:30 AM IST (5:00 UTC)
  workflow_dispatch: # Allows you to manually trigger the action

jobs:
  green-square-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a commit
        run: |
          date >> log.txt
          git config user.name "Aditya-Bot"
          git config user.email "adityaa002@users.noreply.github.com"
          git add .
          git commit -m "Auto commit on $(date)" || echo "No changes to commit"
          git push
